[package]
authors = ["whmountains <8680147+whmountains@users.noreply.github.com>"]
description = "Mailgun client (WIP)"
license = "GPL-3.0"
name = "mailgun"
repository = "https://github.com/whmountains/mailgun-rs"
version = "0.1.3"

[dependencies]
